import type { Metadata } from "next"
import { IBM_Plex_Sans } from "next/font/google"
import "./globals.css"
import Header from "../../components/Header"

const plex = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex flex-row justify-center">
      <div className="min-w-[512px] w-full max-w-2xl">
        <div className="flex flex-col justify-start max-w-2xl px-8 py-24 ">
          <Header />
          <main className="w-full font-medium text-zinc-950">{children}</main>
        </div>
      </div>
    </div>
  )
}
